{
  'test_type': 'output_check',
  'errors': """
raw_error.pwn(1) : fatal error 311: user error: "raw error\\"

Compilation aborted.
"""
}
